services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:3000'
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - PUBLIC_CONTENT_MIN_LENGTH=${PUBLIC_CONTENT_MIN_LENGTH}
      - PUBLIC_CONTENT_MAX_LENGTH=${PUBLIC_CONTENT_MAX_LENGTH}
      - PUBLIC_PASSWORD_MIN_LENGTH=${PUBLIC_PASSWORD_MIN_LENGTH}
      - PUBLIC_PASSWORD_MAX_LENGTH=${PUBLIC_PASSWORD_MAX_LENGTH}
      - PUBLIC_PASSWORD_UPPER_CASE_REQUIRED=${PUBLIC_PASSWORD_UPPER_CASE_REQUIRED}
      - PUBLIC_PASSWORD_LOWER_CASE_REQUIRED=${PUBLIC_PASSWORD_LOWER_CASE_REQUIRED}
      - PUBLIC_PASSWORD_NUMBER_REQUIRED=${PUBLIC_PASSWORD_NUMBER_REQUIRED}
      - PUBLIC_PASSWORD_SPECIAL_CHARACTER_REQUIRED=${PUBLIC_PASSWORD_SPECIAL_CHARACTER_REQUIRED}
      - PUBLIC_VIEWS_MIN=${PUBLIC_VIEWS_MIN}
      - PUBLIC_VIEWS_MAX=${PUBLIC_VIEWS_MAX}
      - PUBLIC_VIEWS_DEFAULT=${PUBLIC_VIEWS_DEFAULT}
      - PUBLIC_VIEWS_SHOW_RECIPIENTS_DEFAULT=${PUBLIC_VIEWS_SHOW_RECIPIENTS_DEFAULT}
      - PUBLIC_VIEWS_UNLIMITED_DEFAULT=${PUBLIC_VIEWS_UNLIMITED_DEFAULT}
      - PUBLIC_EXPIRES_IN_MAX_VALUE=${PUBLIC_EXPIRES_IN_MAX_VALUE}
      - PUBLIC_EXPIRES_IN_MAX_UNIT=${PUBLIC_EXPIRES_IN_MAX_UNIT}
      - PUBLIC_EXPIRES_IN_VALUE_DEFAULT=${PUBLIC_EXPIRES_IN_VALUE_DEFAULT}
      - PUBLIC_EXPIRES_IN_UNIT_DEFAULT=${PUBLIC_EXPIRES_IN_UNIT_DEFAULT}
      - PUBLIC_EXPIRES_IN_SHOW_RECIPIENTS_DEFAULT=${PUBLIC_EXPIRES_IN_SHOW_RECIPIENTS_DEFAULT}
      - PUBLIC_SHOW_COPY_BUTTON_DEFAULT=${PUBLIC_SHOW_COPY_BUTTON_DEFAULT}
      - PUBLIC_SHOW_DOWNLOAD_BUTTON_DEFAULT=${PUBLIC_SHOW_DOWNLOAD_BUTTON_DEFAULT}
      - RATE_LIMITER_IP=${RATE_LIMITER_IP}
      - RATE_LIMITER_IPUA=${RATE_LIMITER_IPUA}
    depends_on:
      mysql:
        condition: service_healthy
        timeout: 60s
    restart: unless-stopped

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./drizzle/0000_normal_exodus.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
